import type { Metadata } from 'next';
import { fontBarlow, fontBarlowCondensed, fontBellefair } from './fonts';
import './globals.css';
import Header from '@/components/header/header';
// import desktopBg from '@/lib/assets/home/background-home-desktop.jpg';
// import tabletBg from '@/lib/assets/home/background-home-tablet.jpg';
// import moileBg from '@/lib/assets/home/background-home-mobile.jpg';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${fontBarlow.variable} ${fontBarlowCondensed.variable} ${fontBellefair.variable} font-barlow  text-primary`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
